from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description() -> LaunchDescription:
    args = [
        DeclareLaunchArgument("tracking_service_name", default_value="/yoloe/set_tracking"),
        DeclareLaunchArgument("people_tracks_2d_topic", default_value="/people_tracks_2d"),
        DeclareLaunchArgument("people_tracks_3d_topic", default_value="/people_tracks_3d"),
        DeclareLaunchArgument("tracking_compat_topic", default_value="/yoloe/tracking_detections"),
        DeclareLaunchArgument("follow_pose_topic", default_value="/people/follow_target_pose"),
        DeclareLaunchArgument("color_topic", default_value="/camera/color/image_raw"),
        DeclareLaunchArgument("depth_topic", default_value="/camera/aligned_depth_to_color/image_raw"),
        DeclareLaunchArgument("camera_info_topic", default_value="/camera/color/camera_info"),
        DeclareLaunchArgument("camera_link_frame", default_value="camera_link"),
        DeclareLaunchArgument("tf_prefix", default_value="person_id"),
        DeclareLaunchArgument("model_path", default_value="/home/usern/robocup_ws/yolo11s.pt"),
        DeclareLaunchArgument("device", default_value="auto"),
        DeclareLaunchArgument("imgsz", default_value="640"),
        DeclareLaunchArgument("det_conf", default_value="0.45"),
        DeclareLaunchArgument("det_iou", default_value="0.50"),
        DeclareLaunchArgument("max_det", default_value="100"),
        DeclareLaunchArgument("tracking_class", default_value="person"),
        DeclareLaunchArgument("enable_open_vocab_prompt", default_value="false"),
        DeclareLaunchArgument("patch_torchvision_nms_cpu_fallback", default_value="true"),
        DeclareLaunchArgument("prefer_ultralytics_torch_nms", default_value="true"),
        DeclareLaunchArgument("max_age", default_value="30"),
        DeclareLaunchArgument("n_init", default_value="3"),
        DeclareLaunchArgument("max_cosine_distance", default_value="0.25"),
        DeclareLaunchArgument("nn_budget", default_value="100"),
        DeclareLaunchArgument("nms_max_overlap", default_value="1.0"),
        DeclareLaunchArgument("reid_embedder", default_value="auto"),
        DeclareLaunchArgument("use_torchreid_embedder", default_value="true"),
        DeclareLaunchArgument("torchreid_model_name", default_value="osnet_ain_x0_5"),
        DeclareLaunchArgument("torchreid_embedder_gpu", default_value="true"),
        DeclareLaunchArgument("clip_model_name", default_value="ViT-B/16"),
        DeclareLaunchArgument("embedder_weights_path", default_value=""),
        DeclareLaunchArgument("fallback_to_hsv_embedder", default_value="true"),
        DeclareLaunchArgument("publish_rate_hz", default_value="0.0"),
        DeclareLaunchArgument("debug_image_dir", default_value="/home/usern/robocup_ws/yoloe_out"),
        DeclareLaunchArgument("debug_save_interval_s", default_value="0.2"),
        DeclareLaunchArgument("enable_ui", default_value="false"),
        DeclareLaunchArgument("ui_window_name", default_value="DeepSORT Tracking"),
        DeclareLaunchArgument("ui_show_depth_text", default_value="true"),
        DeclareLaunchArgument("depth_window_size", default_value="5"),
        DeclareLaunchArgument("min_depth_m", default_value="0.2"),
        DeclareLaunchArgument("max_depth_m", default_value="8.0"),
        DeclareLaunchArgument("max_depth_age_ms", default_value="200.0"),
        DeclareLaunchArgument("lost_hold_sec", default_value="2.0"),
        DeclareLaunchArgument("reacquire_max_dist_m", default_value="1.5"),
        DeclareLaunchArgument("reacquire_max_vel_mps", default_value="1.5"),
        DeclareLaunchArgument("motion_weight", default_value="0.4"),
        DeclareLaunchArgument("diagnostics_period_s", default_value="1.0"),
    ]

    node = Node(
        package="deepsort_people_follow",
        executable="deepsort_people_follow_node",
        name="deepsort_people_follow_node",
        output="screen",
        parameters=[
            {
                "tracking_service_name": LaunchConfiguration("tracking_service_name"),
                "people_tracks_2d_topic": LaunchConfiguration("people_tracks_2d_topic"),
                "people_tracks_3d_topic": LaunchConfiguration("people_tracks_3d_topic"),
                "tracking_compat_topic": LaunchConfiguration("tracking_compat_topic"),
                "follow_pose_topic": LaunchConfiguration("follow_pose_topic"),
                "color_topic": LaunchConfiguration("color_topic"),
                "depth_topic": LaunchConfiguration("depth_topic"),
                "camera_info_topic": LaunchConfiguration("camera_info_topic"),
                "camera_link_frame": LaunchConfiguration("camera_link_frame"),
                "tf_prefix": LaunchConfiguration("tf_prefix"),
                "model_path": LaunchConfiguration("model_path"),
                "device": LaunchConfiguration("device"),
                "imgsz": LaunchConfiguration("imgsz"),
                "det_conf": LaunchConfiguration("det_conf"),
                "det_iou": LaunchConfiguration("det_iou"),
                "max_det": LaunchConfiguration("max_det"),
                "tracking_class": LaunchConfiguration("tracking_class"),
                "enable_open_vocab_prompt": LaunchConfiguration("enable_open_vocab_prompt"),
                "patch_torchvision_nms_cpu_fallback": LaunchConfiguration("patch_torchvision_nms_cpu_fallback"),
                "prefer_ultralytics_torch_nms": LaunchConfiguration("prefer_ultralytics_torch_nms"),
                "max_age": LaunchConfiguration("max_age"),
                "n_init": LaunchConfiguration("n_init"),
                "max_cosine_distance": LaunchConfiguration("max_cosine_distance"),
                "nn_budget": LaunchConfiguration("nn_budget"),
                "nms_max_overlap": LaunchConfiguration("nms_max_overlap"),
                "reid_embedder": LaunchConfiguration("reid_embedder"),
                "use_torchreid_embedder": LaunchConfiguration("use_torchreid_embedder"),
                "torchreid_model_name": LaunchConfiguration("torchreid_model_name"),
                "torchreid_embedder_gpu": LaunchConfiguration("torchreid_embedder_gpu"),
                "clip_model_name": LaunchConfiguration("clip_model_name"),
                "embedder_weights_path": LaunchConfiguration("embedder_weights_path"),
                "fallback_to_hsv_embedder": LaunchConfiguration("fallback_to_hsv_embedder"),
                "publish_rate_hz": LaunchConfiguration("publish_rate_hz"),
                "debug_image_dir": LaunchConfiguration("debug_image_dir"),
                "debug_save_interval_s": LaunchConfiguration("debug_save_interval_s"),
                "enable_ui": LaunchConfiguration("enable_ui"),
                "ui_window_name": LaunchConfiguration("ui_window_name"),
                "ui_show_depth_text": LaunchConfiguration("ui_show_depth_text"),
                "depth_window_size": LaunchConfiguration("depth_window_size"),
                "min_depth_m": LaunchConfiguration("min_depth_m"),
                "max_depth_m": LaunchConfiguration("max_depth_m"),
                "max_depth_age_ms": LaunchConfiguration("max_depth_age_ms"),
                "lost_hold_sec": LaunchConfiguration("lost_hold_sec"),
                "reacquire_max_dist_m": LaunchConfiguration("reacquire_max_dist_m"),
                "reacquire_max_vel_mps": LaunchConfiguration("reacquire_max_vel_mps"),
                "motion_weight": LaunchConfiguration("motion_weight"),
                "diagnostics_period_s": LaunchConfiguration("diagnostics_period_s"),
            }
        ],
    )

    return LaunchDescription(args + [node])
