from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.conditions import IfCondition
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description() -> LaunchDescription:
    args = [
        DeclareLaunchArgument("tracking_service_name", default_value="/yoloe/set_tracking"),
        DeclareLaunchArgument("people_tracks_2d_topic", default_value="/people_tracks_2d"),
        DeclareLaunchArgument("people_tracks_3d_topic", default_value="/people_tracks_3d"),
        DeclareLaunchArgument("tracking_compat_topic", default_value="/yoloe/tracking_detections"),
        DeclareLaunchArgument("follow_pose_topic", default_value="/people/follow_target_pose"),
        DeclareLaunchArgument("color_topic", default_value="/camera0/color/image_raw"),
        DeclareLaunchArgument("depth_topic", default_value="/camera0/depth/image_rect_raw"),
        DeclareLaunchArgument("camera_info_topic", default_value="/camera0/color/camera_info"),
        DeclareLaunchArgument("camera_link_frame", default_value="camera0_link"),
        DeclareLaunchArgument("tf_prefix", default_value="person_id"),
        DeclareLaunchArgument("model_path", default_value="/home/usern/robocup_ws/yolo11n.pt"),
        DeclareLaunchArgument("device", default_value="cuda:0"),
        DeclareLaunchArgument("imgsz", default_value="416"),
        DeclareLaunchArgument("det_conf", default_value="0.45"),
        DeclareLaunchArgument("det_iou", default_value="0.50"),
        DeclareLaunchArgument("max_det", default_value="100"),
        DeclareLaunchArgument("tracking_class", default_value="person"),
        DeclareLaunchArgument("enable_open_vocab_prompt", default_value="false"),
        DeclareLaunchArgument("patch_torchvision_nms_cpu_fallback", default_value="true"),
        DeclareLaunchArgument("prefer_ultralytics_torch_nms", default_value="true"),
        DeclareLaunchArgument("max_age", default_value="75"),
        DeclareLaunchArgument("n_init", default_value="2"),
        DeclareLaunchArgument("max_cosine_distance", default_value="0.20"),
        DeclareLaunchArgument("nn_budget", default_value="150"),
        DeclareLaunchArgument("nms_max_overlap", default_value="1.0"),
        DeclareLaunchArgument("reid_embedder", default_value="torchreid"),
        DeclareLaunchArgument("use_torchreid_embedder", default_value="true"),
        DeclareLaunchArgument("torchreid_model_name", default_value="osnet_ain_x1_0"),
        DeclareLaunchArgument("torchreid_embedder_gpu", default_value="true"),
        DeclareLaunchArgument("clip_model_name", default_value="ViT-B/16"),
        DeclareLaunchArgument(
            "embedder_weights_path",
            default_value="/home/usern/.cache/torch/checkpoints/osnet_ain_x1_0_imagenet.pth",
        ),
        DeclareLaunchArgument("fallback_to_hsv_embedder", default_value="true"),
        DeclareLaunchArgument("publish_rate_hz", default_value="18.0"),
        DeclareLaunchArgument("debug_image_dir", default_value="/home/usern/robocup_ws/yoloe_out"),
        DeclareLaunchArgument("debug_save_interval_s", default_value="0.2"),
        DeclareLaunchArgument("enable_ui", default_value="true"),
        DeclareLaunchArgument("ui_window_name", default_value="DeepSORT Tracking"),
        DeclareLaunchArgument("ui_show_depth_text", default_value="true"),
        DeclareLaunchArgument("max_input_color_rate_hz", default_value="24.0"),
        DeclareLaunchArgument("max_input_depth_rate_hz", default_value="18.0"),
        DeclareLaunchArgument("depth_window_size", default_value="5"),
        DeclareLaunchArgument("min_depth_m", default_value="0.2"),
        DeclareLaunchArgument("max_depth_m", default_value="8.0"),
        DeclareLaunchArgument("max_depth_age_ms", default_value="100.0"),
        DeclareLaunchArgument("lost_hold_sec", default_value="1.0"),
        DeclareLaunchArgument("reacquire_max_dist_m", default_value="2.2"),
        DeclareLaunchArgument("reacquire_max_vel_mps", default_value="1.0"),
        DeclareLaunchArgument("motion_weight", default_value="0.15"),
        DeclareLaunchArgument("diagnostics_period_s", default_value="1.0"),
        DeclareLaunchArgument("launch_nav2_bridge", default_value="true"),
        DeclareLaunchArgument("nav2_bridge_enabled", default_value="false"),
        DeclareLaunchArgument("nav2_bridge_global_frame", default_value="map"),
        DeclareLaunchArgument("nav2_bridge_robot_base_frame", default_value="base_footprint"),
        DeclareLaunchArgument("nav2_bridge_tracked_frame", default_value="follow_target"),
        DeclareLaunchArgument("nav2_bridge_goal_command_mode", default_value="navigate_to_pose"),
        DeclareLaunchArgument("nav2_bridge_goal_pose_topic", default_value="/goal_pose"),
        DeclareLaunchArgument("nav2_bridge_goal_update_topic", default_value="/goal_update"),
        DeclareLaunchArgument("nav2_bridge_navigate_to_pose_action", default_value="/navigate_to_pose"),
        DeclareLaunchArgument("nav2_bridge_enable_service_name", default_value="/people_follow_nav2/set_enabled"),
        DeclareLaunchArgument("nav2_bridge_goal_update_rate_hz", default_value="10.0"),
        DeclareLaunchArgument("nav2_bridge_goal_republish_period_s", default_value="0.0"),
        DeclareLaunchArgument("nav2_bridge_min_goal_translation_delta_m", default_value="0.05"),
        DeclareLaunchArgument("nav2_bridge_min_goal_yaw_delta_rad", default_value="0.12"),
        DeclareLaunchArgument("nav2_bridge_follow_standoff_distance_m", default_value="0.7"),
        DeclareLaunchArgument("nav2_bridge_follow_distance_tolerance_m", default_value="0.10"),
        DeclareLaunchArgument("nav2_bridge_target_smoothing_alpha", default_value="0.65"),
        DeclareLaunchArgument("nav2_bridge_target_smoothing_reset_distance_m", default_value="0.40"),
        DeclareLaunchArgument("nav2_bridge_publish_hold_goal_on_disable", default_value="true"),
        DeclareLaunchArgument("nav2_bridge_transform_timeout_s", default_value="0.2"),
        DeclareLaunchArgument("nav2_bridge_target_lost_timeout_s", default_value="2.0"),
        DeclareLaunchArgument(
            "nav2_bridge_behavior_tree_path",
            default_value="/workspaces/isaac_ros-dev/src/wheeltec_robot_nav2/param/bt/follower_w_recovery.xml",
        ),
        DeclareLaunchArgument("nav2_bridge_behavior_tree_package", default_value="deepsort_people_follow"),
        DeclareLaunchArgument(
            "nav2_bridge_behavior_tree_relative_path",
            default_value="bt/follower_w_recovery.xml",
        ),
    ]

    node = Node(
        package="deepsort_people_follow",
        executable="deepsort_people_follow_node",
        name="deepsort_people_follow_node",
        output="screen",
        parameters=[
            {
                "tracking_service_name": LaunchConfiguration("tracking_service_name"),
                "people_tracks_2d_topic": LaunchConfiguration("people_tracks_2d_topic"),
                "people_tracks_3d_topic": LaunchConfiguration("people_tracks_3d_topic"),
                "tracking_compat_topic": LaunchConfiguration("tracking_compat_topic"),
                "follow_pose_topic": LaunchConfiguration("follow_pose_topic"),
                "color_topic": LaunchConfiguration("color_topic"),
                "depth_topic": LaunchConfiguration("depth_topic"),
                "camera_info_topic": LaunchConfiguration("camera_info_topic"),
                "camera_link_frame": LaunchConfiguration("camera_link_frame"),
                "tf_prefix": LaunchConfiguration("tf_prefix"),
                "model_path": LaunchConfiguration("model_path"),
                "device": LaunchConfiguration("device"),
                "imgsz": LaunchConfiguration("imgsz"),
                "det_conf": LaunchConfiguration("det_conf"),
                "det_iou": LaunchConfiguration("det_iou"),
                "max_det": LaunchConfiguration("max_det"),
                "tracking_class": LaunchConfiguration("tracking_class"),
                "enable_open_vocab_prompt": LaunchConfiguration("enable_open_vocab_prompt"),
                "patch_torchvision_nms_cpu_fallback": LaunchConfiguration("patch_torchvision_nms_cpu_fallback"),
                "prefer_ultralytics_torch_nms": LaunchConfiguration("prefer_ultralytics_torch_nms"),
                "max_age": LaunchConfiguration("max_age"),
                "n_init": LaunchConfiguration("n_init"),
                "max_cosine_distance": LaunchConfiguration("max_cosine_distance"),
                "nn_budget": LaunchConfiguration("nn_budget"),
                "nms_max_overlap": LaunchConfiguration("nms_max_overlap"),
                "reid_embedder": LaunchConfiguration("reid_embedder"),
                "use_torchreid_embedder": LaunchConfiguration("use_torchreid_embedder"),
                "torchreid_model_name": LaunchConfiguration("torchreid_model_name"),
                "torchreid_embedder_gpu": LaunchConfiguration("torchreid_embedder_gpu"),
                "clip_model_name": LaunchConfiguration("clip_model_name"),
                "embedder_weights_path": LaunchConfiguration("embedder_weights_path"),
                "fallback_to_hsv_embedder": LaunchConfiguration("fallback_to_hsv_embedder"),
                "publish_rate_hz": LaunchConfiguration("publish_rate_hz"),
                "debug_image_dir": LaunchConfiguration("debug_image_dir"),
                "debug_save_interval_s": LaunchConfiguration("debug_save_interval_s"),
                "enable_ui": LaunchConfiguration("enable_ui"),
                "ui_window_name": LaunchConfiguration("ui_window_name"),
                "ui_show_depth_text": LaunchConfiguration("ui_show_depth_text"),
                "max_input_color_rate_hz": LaunchConfiguration("max_input_color_rate_hz"),
                "max_input_depth_rate_hz": LaunchConfiguration("max_input_depth_rate_hz"),
                "depth_window_size": LaunchConfiguration("depth_window_size"),
                "min_depth_m": LaunchConfiguration("min_depth_m"),
                "max_depth_m": LaunchConfiguration("max_depth_m"),
                "max_depth_age_ms": LaunchConfiguration("max_depth_age_ms"),
                "lost_hold_sec": LaunchConfiguration("lost_hold_sec"),
                "reacquire_max_dist_m": LaunchConfiguration("reacquire_max_dist_m"),
                "reacquire_max_vel_mps": LaunchConfiguration("reacquire_max_vel_mps"),
                "motion_weight": LaunchConfiguration("motion_weight"),
                "diagnostics_period_s": LaunchConfiguration("diagnostics_period_s"),
            }
        ],
    )

    nav2_bridge_node = Node(
        package="deepsort_people_follow",
        executable="people_follow_nav2_bridge",
        name="people_follow_nav2_bridge",
        output="screen",
        condition=IfCondition(LaunchConfiguration("launch_nav2_bridge")),
        parameters=[
            {
                "enabled": LaunchConfiguration("nav2_bridge_enabled"),
                "global_frame": LaunchConfiguration("nav2_bridge_global_frame"),
                "robot_base_frame": LaunchConfiguration("nav2_bridge_robot_base_frame"),
                "tracked_frame": LaunchConfiguration("nav2_bridge_tracked_frame"),
                "goal_command_mode": LaunchConfiguration("nav2_bridge_goal_command_mode"),
                "goal_pose_topic": LaunchConfiguration("nav2_bridge_goal_pose_topic"),
                "goal_update_topic": LaunchConfiguration("nav2_bridge_goal_update_topic"),
                "navigate_to_pose_action": LaunchConfiguration("nav2_bridge_navigate_to_pose_action"),
                "enable_service_name": LaunchConfiguration("nav2_bridge_enable_service_name"),
                "goal_update_rate_hz": LaunchConfiguration("nav2_bridge_goal_update_rate_hz"),
                "goal_republish_period_s": LaunchConfiguration("nav2_bridge_goal_republish_period_s"),
                "min_goal_translation_delta_m": LaunchConfiguration("nav2_bridge_min_goal_translation_delta_m"),
                "min_goal_yaw_delta_rad": LaunchConfiguration("nav2_bridge_min_goal_yaw_delta_rad"),
                "follow_standoff_distance_m": LaunchConfiguration("nav2_bridge_follow_standoff_distance_m"),
                "follow_distance_tolerance_m": LaunchConfiguration("nav2_bridge_follow_distance_tolerance_m"),
                "target_smoothing_alpha": LaunchConfiguration("nav2_bridge_target_smoothing_alpha"),
                "target_smoothing_reset_distance_m": LaunchConfiguration(
                    "nav2_bridge_target_smoothing_reset_distance_m"
                ),
                "publish_hold_goal_on_disable": LaunchConfiguration("nav2_bridge_publish_hold_goal_on_disable"),
                "transform_timeout_s": LaunchConfiguration("nav2_bridge_transform_timeout_s"),
                "target_lost_timeout_s": LaunchConfiguration("nav2_bridge_target_lost_timeout_s"),
                "behavior_tree_path": LaunchConfiguration("nav2_bridge_behavior_tree_path"),
                "behavior_tree_package": LaunchConfiguration("nav2_bridge_behavior_tree_package"),
                "behavior_tree_relative_path": LaunchConfiguration("nav2_bridge_behavior_tree_relative_path"),
            }
        ],
    )

    return LaunchDescription(args + [node, nav2_bridge_node])
